/* tslint:disable */
/* eslint-disable */
/**
 * Barber App API
 * An API for Barber App 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InfoRequest
 */
export interface InfoRequest {
    /**
     * 
     * @type {string}
     * @memberof InfoRequest
     */
    newEmail?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InfoRequest
     */
    newPassword?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InfoRequest
     */
    oldPassword?: string | null;
}
