/* tslint:disable */
/* eslint-disable */
/**
 * Barber App API
 * An API for Barber App 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DateOnly } from './date-only';
import { TimeSpan } from './time-span';
/**
 * 
 * @export
 * @interface Reservation
 */
export interface Reservation {
    /**
     * 
     * @type {string}
     * @memberof Reservation
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Reservation
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof Reservation
     */
    lastName?: string | null;
    /**
     * 
     * @type {DateOnly}
     * @memberof Reservation
     */
    date: DateOnly;
    /**
     * 
     * @type {TimeSpan}
     * @memberof Reservation
     */
    time: TimeSpan;
    /**
     * 
     * @type {string}
     * @memberof Reservation
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Reservation
     */
    phone: string;
    /**
     * 
     * @type {string}
     * @memberof Reservation
     */
    service: string;
    /**
     * 
     * @type {string}
     * @memberof Reservation
     */
    userId?: string | null;
}
