/* tslint:disable */
/* eslint-disable */
/**
 * Barber App API
 * An API for Barber App 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ReservationIM
 */
export interface ReservationIM {
    /**
     * 
     * @type {string}
     * @memberof ReservationIM
     */
    date: string;
    /**
     * 
     * @type {number}
     * @memberof ReservationIM
     */
    time: number;
    /**
     * 
     * @type {string}
     * @memberof ReservationIM
     */
    service: string;
}
