/* tslint:disable */
/* eslint-disable */
/**
 * Barber App API
 * An API for Barber App 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ReservationVM
 */
export interface ReservationVM {
    /**
     * 
     * @type {string}
     * @memberof ReservationVM
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof ReservationVM
     */
    lastName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ReservationVM
     */
    date: string;
    /**
     * 
     * @type {number}
     * @memberof ReservationVM
     */
    time: number;
    /**
     * 
     * @type {string}
     * @memberof ReservationVM
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof ReservationVM
     */
    phone: string;
    /**
     * 
     * @type {string}
     * @memberof ReservationVM
     */
    service: string;
}
