/* tslint:disable */
/* eslint-disable */
/**
 * Barber App API
 * An API for Barber App 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UserUM
 */
export interface UserUM {
    /**
     * 
     * @type {string}
     * @memberof UserUM
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof UserUM
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof UserUM
     */
    phoneNumber: string;
}
