/* tslint:disable */
/* eslint-disable */
/**
 * Barber App API
 * An API for Barber App 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UserVM
 */
export interface UserVM {
    /**
     * 
     * @type {string}
     * @memberof UserVM
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserVM
     */
    firstName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserVM
     */
    lastName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserVM
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserVM
     */
    phoneNumber?: string | null;
}
