/* tslint:disable */
/* eslint-disable */
/**
 * BA.Application
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UserIM
 */
export interface UserIM {
    /**
     * 
     * @type {string}
     * @memberof UserIM
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof UserIM
     */
    lastName: string;
}
